### ISSUE TITLE
Version not compatible

### ISSUE THREAD

**Issue by falceso** [Cosmic-Networks/CosmicFreedomMod#1]
Currently the released jars do not work on 1.10.2 R_1

Error Log:
https://codebin.falceso.tk/view/0b5573f6

**Comment by Ahrics** [comment]
@falceso this plugin only works on 1.9 servers.
For your 1.10 server, please switch it to 1.9.2.
*After switching it, add ViaVersion (optional)*

**Comment by falceso** [comment]
TODO:

- Add 1.10.2 plugin version compile...
